# Generated by Django 2.0 on 2017-12-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=10)),
                ('Jan_expr', models.FloatField(default=0)),
                ('GTE_expr', models.FloatField(default=0)),
                ('TCGAN_expr', models.FloatField(default=0)),
            ],
        ),
    ]
