# Generated by Django 2.0 on 2017-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0002_auto_20171224_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='GTE_expr',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='gene',
            name='Jan_expr',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='gene',
            name='TCGAN_expr',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='gene',
            name='rev_ann',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
